---
#cloud-config
autoinstall:
    version: 1
    # locale: pt_BR.UTF-8
    locale: en_US.UTF-8
    timezone: America/Sao_Paulo

    keyboard:
        layout: br

    packages:
        - build-essential
        - ca-certificates
        - curl
        - dash
        - flameshot
        - git
        - git-lfs
        - gnome-clocks
        - gnome-shell-extension-manager
        - gnome-shell-extensions
        - gnome-tweaks
        - gnome-weather
        - htop
        - kdenlive
        - make
        - nodejs
        - postgresql
        - postgresql-contrib
        - python3-pip
        - python3-venv
        - remmina
        - snapd
        - software-properties-common
        - tilix
        - traceroute
        - transmission-gtk
        - tree
        - unzip
        - vim
        - vlc
        - wget
        - whois
        - zsh

    snaps:
        - name: brave
        - name: dbeaver-ce
        - name: discord
        - name: postman

    identity:
        realname: "User"
        username: user
        password: $y$j9T$FnwitrYOiBEcaMok75FIs.$3XxOYKBAHRyid5X7gMtwCevTrkpUHSYgdmNeCTI/kE6
        hostname: computer

    storage:
        layout:
            name: direct

    early-commands:
        - echo 'linux-generic-hwe-24.04' > /run/kernel-meta-package

    late-commands:
        - curtin in-target -- apt purge aisleriot gnome-mines gnome-mahjongg gnome-sudoku thunderbird rhythmbox shotwell simple-scan thunar totem gnome-power-manager -y
        - curtin in-target -- apt purge  -y
        - curtin in-target -- apt autoremove --purge -y
        - curtin in-target -- apt update
        - curtin in-target -- apt upgrade -y
        - curtin in-target -- apt autoremove -y
        - curtin in-target -- apt autoclean -y

    shutdown: reboot
